import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { NavLink } from 'react-router-dom';
import { shortAddress } from '../utils';
const TABS = [
    { path: '/lending/markets', label: 'Markets' },
    { path: '/lending/positions', label: 'Positions' },
];
export function Header({ account, isConnected, chainId, isWrongNetwork, expectedChainId, expectedNetwork, onSwitchNetwork, switchingNetwork, onConnect, onDisconnect, }) {
    return (_jsx("header", { className: "sticky top-0 z-50 border-b border-zinc-700/80 bg-zinc-900/95 backdrop-blur", children: _jsxs("div", { className: "mx-auto flex h-16 max-w-6xl items-center justify-between px-4 sm:px-6", children: [_jsxs(NavLink, { to: "/lending/markets", className: "flex items-center gap-2", children: [_jsx("div", { className: "flex h-9 w-9 items-center justify-center rounded-lg bg-teal-500/20 text-teal-400 font-semibold", children: "\u25C8" }), _jsx("span", { className: "text-lg font-semibold text-white", children: "Lending" })] }), _jsx("nav", { className: "flex gap-0.5", children: TABS.map(({ path, label }) => (_jsx(NavLink, { to: path, end: true, className: ({ isActive }) => `rounded-lg px-4 py-2 text-sm font-medium transition-colors ${isActive ? 'bg-zinc-700 text-white' : 'text-zinc-400 hover:bg-zinc-800 hover:text-zinc-200'}`, children: label }, path))) }), _jsx("div", { children: isConnected && account ? (_jsxs("div", { className: "flex items-center gap-3", children: [_jsxs("span", { className: "hidden text-right sm:block", children: [_jsxs("span", { className: "block text-xs text-zinc-500", children: ["Connected ", chainId != null ? `(Chain ${chainId})` : ''] }), _jsx("span", { className: "font-mono text-sm text-zinc-200", children: shortAddress(account) })] }), isWrongNetwork && (_jsx("button", { type: "button", onClick: onSwitchNetwork, disabled: switchingNetwork, className: "rounded-lg bg-amber-600 px-3 py-2 text-xs font-semibold text-white hover:bg-amber-500 disabled:opacity-50", title: `Switch to ${expectedNetwork} (${expectedChainId})`, children: switchingNetwork ? 'Switching...' : `Switch to ${expectedNetwork}` })), _jsx("button", { type: "button", onClick: onDisconnect, className: "rounded-lg bg-red-600/90 px-4 py-2 text-sm font-medium text-white hover:bg-red-500", children: "Disconnect" })] })) : (_jsx("button", { type: "button", onClick: onConnect, className: "rounded-lg bg-teal-600 px-4 py-2 text-sm font-medium text-white hover:bg-teal-500", children: "Connect Wallet" })) })] }) }));
}
