import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export const Header = ({ account, isConnected, onConnect, onDisconnect, activeTab, setActiveTab, }) => {
    const formatAddress = (addr) => {
        return `${addr.substring(0, 6)}...${addr.substring(addr.length - 4)}`;
    };
    return (_jsx("header", { className: "bg-gradient-to-b from-slate-800 to-slate-900 border-b border-slate-700 sticky top-0 z-50", children: _jsxs("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8", children: [_jsxs("div", { className: "flex justify-between items-center h-20", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "w-10 h-10 rounded-full bg-gradient-to-br from-pink-500 to-purple-600 flex items-center justify-center", children: _jsx("span", { className: "text-white font-bold text-lg", children: "\uD83D\uDCB0" }) }), _jsx("h1", { className: "text-2xl font-bold bg-gradient-to-r from-pink-500 to-purple-600 bg-clip-text text-transparent", children: "DeFi Lending" })] }), _jsxs("nav", { className: "hidden md:flex gap-1", children: [_jsx("button", { onClick: () => setActiveTab('markets'), className: `px-4 py-2 rounded-lg font-medium transition-colors ${activeTab === 'markets'
                                        ? 'text-white bg-slate-700'
                                        : 'text-gray-400 hover:text-white hover:bg-slate-800'}`, children: "Markets" }), _jsx("button", { onClick: () => setActiveTab('positions'), className: `px-4 py-2 rounded-lg font-medium transition-colors ${activeTab === 'positions'
                                        ? 'text-white bg-slate-700'
                                        : 'text-gray-400 hover:text-white hover:bg-slate-800'}`, children: "Positions" })] }), _jsx("div", { children: isConnected && account ? (_jsxs("div", { className: "flex items-center gap-3", children: [_jsxs("div", { className: "hidden sm:block text-right", children: [_jsx("p", { className: "text-sm text-gray-400", children: "Connected" }), _jsx("p", { className: "text-sm font-semibold text-white", children: formatAddress(account) })] }), _jsx("button", { onClick: onDisconnect, className: "px-4 py-2 rounded-lg bg-red-500 hover:bg-red-600 text-white font-medium transition-colors", children: "Disconnect" })] })) : (_jsx("button", { onClick: onConnect, className: "px-6 py-2 rounded-lg bg-gradient-to-r from-pink-500 to-purple-600 hover:from-pink-600 hover:to-purple-700 text-white font-medium transition-colors", children: "Connect" })) })] }), _jsxs("div", { className: "md:hidden flex gap-1 pb-4 overflow-x-auto", children: [_jsx("button", { onClick: () => setActiveTab('markets'), className: `px-4 py-2 rounded-lg font-medium transition-colors whitespace-nowrap ${activeTab === 'markets'
                                ? 'text-white bg-slate-700'
                                : 'text-gray-400 hover:text-white hover:bg-slate-800'}`, children: "Markets" }), _jsx("button", { onClick: () => setActiveTab('positions'), className: `px-4 py-2 rounded-lg font-medium transition-colors whitespace-nowrap ${activeTab === 'positions'
                                ? 'text-white bg-slate-700'
                                : 'text-gray-400 hover:text-white hover:bg-slate-800'}`, children: "Positions" })] })] }) }));
};
