import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export const UserPositions = ({ account, loading, connected, onWithdraw, onRepay, }) => {
    if (!connected) {
        return (_jsx("div", { className: "bg-slate-800 rounded-lg p-8 text-center", children: _jsx("p", { className: "text-gray-400", children: "\u8BF7\u5148\u8FDE\u63A5\u94B1\u5305" }) }));
    }
    if (loading) {
        return (_jsxs("div", { className: "bg-slate-800 rounded-lg p-8 text-center", children: [_jsx("div", { className: "animate-spin h-8 w-8 border-4 border-blue-500 border-t-transparent rounded-full mx-auto" }), _jsx("p", { className: "mt-4 text-gray-400", children: "\u52A0\u8F7D\u6301\u4ED3\u6570\u636E..." })] }));
    }
    if (!account || account.positions.length === 0) {
        return (_jsx("div", { className: "bg-slate-800 rounded-lg p-8 text-center", children: _jsx("p", { className: "text-gray-400", children: "\u6682\u65E0\u6301\u4ED3" }) }));
    }
    const supplyPositions = account.positions.filter((p) => p.supplyUnderlying > 0);
    const borrowPositions = account.positions.filter((p) => p.borrowBalance > 0);
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "grid grid-cols-1 md:grid-cols-4 gap-4", children: [_jsxs("div", { className: "bg-gradient-to-br from-slate-800 to-slate-900 rounded-lg p-4 border border-slate-700", children: [_jsx("div", { className: "text-gray-400 text-sm mb-1", children: "\u603B\u5B58\u6B3E" }), _jsxs("div", { className: "text-2xl font-bold text-white", children: ["$", account.totalSupplied.toLocaleString(undefined, { maximumFractionDigits: 2 })] })] }), _jsxs("div", { className: "bg-gradient-to-br from-slate-800 to-slate-900 rounded-lg p-4 border border-slate-700", children: [_jsx("div", { className: "text-gray-400 text-sm mb-1", children: "\u603B\u501F\u6B3E" }), _jsxs("div", { className: "text-2xl font-bold text-white", children: ["$", account.totalBorrowed.toLocaleString(undefined, { maximumFractionDigits: 2 })] })] }), _jsxs("div", { className: "bg-gradient-to-br from-slate-800 to-slate-900 rounded-lg p-4 border border-slate-700", children: [_jsx("div", { className: "text-gray-400 text-sm mb-1", children: "\u501F\u6B3E\u989D\u5EA6" }), _jsxs("div", { className: "text-2xl font-bold text-white", children: ["$", account.borrowLimit.toLocaleString(undefined, { maximumFractionDigits: 2 })] })] }), _jsxs("div", { className: "bg-gradient-to-br from-slate-800 to-slate-900 rounded-lg p-4 border border-slate-700", children: [_jsx("div", { className: "text-gray-400 text-sm mb-1", children: "\u8D26\u6237\u5065\u5EB7\u5EA6" }), _jsx("div", { className: `text-2xl font-bold ${account.isHealthy ? 'text-green-400' : 'text-red-400'}`, children: account.isHealthy ? '健康' : '风险' })] })] }), supplyPositions.length > 0 && (_jsxs("div", { children: [_jsx("h3", { className: "text-xl font-bold mb-4", children: "\u5B58\u6B3E\u6301\u4ED3" }), _jsx("div", { className: "bg-slate-800 rounded-lg overflow-hidden", children: _jsxs("table", { className: "w-full", children: [_jsx("thead", { className: "bg-slate-700", children: _jsxs("tr", { children: [_jsx("th", { className: "px-6 py-3 text-left text-xs font-medium text-gray-300 uppercase", children: "\u8D44\u4EA7" }), _jsx("th", { className: "px-6 py-3 text-right text-xs font-medium text-gray-300 uppercase", children: "\u4F59\u989D" }), _jsx("th", { className: "px-6 py-3 text-right text-xs font-medium text-gray-300 uppercase", children: "\u4EF7\u503C(USD)" }), _jsx("th", { className: "px-6 py-3 text-right text-xs font-medium text-gray-300 uppercase", children: "APY" }), _jsx("th", { className: "px-6 py-3 text-right text-xs font-medium text-gray-300 uppercase", children: "\u62B5\u62BC\u7CFB\u6570" }), _jsx("th", { className: "px-6 py-3 text-right text-xs font-medium text-gray-300 uppercase", children: "\u64CD\u4F5C" })] }) }), _jsx("tbody", { className: "divide-y divide-slate-700", children: supplyPositions.map((position) => {
                                        const valueUSD = (position.supplyUnderlying * position.price) / 1e8;
                                        const balance = (position.supplyUnderlying / (10 ** position.decimals)).toFixed(4);
                                        return (_jsxs("tr", { className: "hover:bg-slate-750", children: [_jsx("td", { className: "px-6 py-4", children: _jsx("div", { className: "font-medium text-white", children: position.symbol }) }), _jsx("td", { className: "px-6 py-4 text-right text-white", children: balance }), _jsxs("td", { className: "px-6 py-4 text-right text-white", children: ["$", valueUSD.toLocaleString(undefined, { maximumFractionDigits: 2 })] }), _jsxs("td", { className: "px-6 py-4 text-right text-green-400", children: [(position.supplyAPY * 100).toFixed(2), "%"] }), _jsxs("td", { className: "px-6 py-4 text-right text-gray-300", children: [(position.collateralFactor * 100).toFixed(0), "%"] }), _jsx("td", { className: "px-6 py-4 text-right", children: _jsx("button", { onClick: () => onWithdraw(position), className: "px-3 py-1 bg-red-600 hover:bg-red-700 text-white text-sm rounded transition-colors", children: "\u53D6\u6B3E" }) })] }, position.market));
                                    }) })] }) })] })), borrowPositions.length > 0 && (_jsxs("div", { children: [_jsx("h3", { className: "text-xl font-bold mb-4", children: "\u501F\u6B3E\u6301\u4ED3" }), _jsx("div", { className: "bg-slate-800 rounded-lg overflow-hidden", children: _jsxs("table", { className: "w-full", children: [_jsx("thead", { className: "bg-slate-700", children: _jsxs("tr", { children: [_jsx("th", { className: "px-6 py-3 text-left text-xs font-medium text-gray-300 uppercase", children: "\u8D44\u4EA7" }), _jsx("th", { className: "px-6 py-3 text-right text-xs font-medium text-gray-300 uppercase", children: "\u501F\u6B3E\u91D1\u989D" }), _jsx("th", { className: "px-6 py-3 text-right text-xs font-medium text-gray-300 uppercase", children: "\u4EF7\u503C(USD)" }), _jsx("th", { className: "px-6 py-3 text-right text-xs font-medium text-gray-300 uppercase", children: "APY" }), _jsx("th", { className: "px-6 py-3 text-right text-xs font-medium text-gray-300 uppercase", children: "\u64CD\u4F5C" })] }) }), _jsx("tbody", { className: "divide-y divide-slate-700", children: borrowPositions.map((position) => {
                                        const valueUSD = (position.borrowBalance * position.price) / 1e8;
                                        const balance = (position.borrowBalance / (10 ** position.decimals)).toFixed(4);
                                        return (_jsxs("tr", { className: "hover:bg-slate-750", children: [_jsx("td", { className: "px-6 py-4", children: _jsx("div", { className: "font-medium text-white", children: position.symbol }) }), _jsx("td", { className: "px-6 py-4 text-right text-white", children: balance }), _jsxs("td", { className: "px-6 py-4 text-right text-white", children: ["$", valueUSD.toLocaleString(undefined, { maximumFractionDigits: 2 })] }), _jsxs("td", { className: "px-6 py-4 text-right text-yellow-400", children: [(position.borrowAPY * 100).toFixed(2), "%"] }), _jsx("td", { className: "px-6 py-4 text-right", children: _jsx("button", { onClick: () => onRepay(position), className: "px-3 py-1 bg-blue-600 hover:bg-blue-700 text-white text-sm rounded transition-colors", children: "\u8FD8\u6B3E" }) })] }, position.market));
                                    }) })] }) })] }))] }));
};
