import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { NavLink } from 'react-router-dom';
const TABS = [
    { path: '/mining/pools', label: 'Pools' },
    { path: '/mining/portfolio', label: 'Portfolio' },
    { path: '/mining/stake', label: '⛏️ Stake GOV' },
    { path: '/mining/transactions', label: 'Transactions' },
    { path: '/mining/analytics', label: '📊 Analytics' },
];
export const Header = ({ wallet, loading, switchingNetwork, isWrongNetwork, expectedNetwork, expectedChainId, onConnect, onDisconnect, onSwitchNetwork, }) => {
    const formatAddress = (address) => {
        return `${address.slice(0, 6)}...${address.slice(-4)}`;
    };
    return (_jsx("header", { className: "bg-gradient-to-b from-slate-800 to-slate-900 border-b border-slate-700 sticky top-0 z-50", children: _jsxs("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8", children: [_jsxs("div", { className: "flex items-center justify-between h-20", children: [_jsxs(NavLink, { to: "/mining/pools", className: "flex items-center gap-3", children: [_jsx("div", { className: "w-10 h-10 rounded-full bg-gradient-to-br from-pink-500 to-purple-600 flex items-center justify-center", children: _jsx("span", { className: "text-white font-bold", children: "L" }) }), _jsx("h1", { className: "text-2xl font-bold bg-gradient-to-r from-pink-500 to-purple-600 bg-clip-text text-transparent", children: "LiquidityMining" })] }), _jsx("nav", { className: "hidden md:flex gap-1", children: TABS.map(({ path, label }) => (_jsx(NavLink, { to: path, end: path === '/mining/pools', className: ({ isActive }) => `px-4 py-2 rounded-lg font-medium transition-colors ${isActive ? 'text-white bg-slate-700' : 'text-gray-400 hover:text-white hover:bg-slate-800'}`, children: label }, path))) }), _jsx("div", { children: wallet.isConnected ? (_jsxs("div", { className: "flex items-center gap-3", children: [_jsxs("div", { className: "hidden sm:block text-right", children: [_jsxs("p", { className: "text-sm text-gray-400", children: ["Connected ", wallet.chainId != null ? `(Chain ${wallet.chainId})` : ''] }), _jsx("p", { className: "text-sm font-semibold text-white", children: formatAddress(wallet.account) })] }), isWrongNetwork && (_jsx("button", { onClick: onSwitchNetwork, disabled: switchingNetwork, className: "px-3 py-2 rounded-lg bg-amber-500 hover:bg-amber-600 disabled:opacity-50 text-white font-medium transition-colors text-xs", title: `Switch to ${expectedNetwork} (${expectedChainId})`, children: switchingNetwork ? 'Switching...' : `Switch to ${expectedNetwork}` })), _jsx("button", { onClick: onDisconnect, className: "px-4 py-2 rounded-lg bg-red-500 hover:bg-red-600 text-white font-medium transition-colors", children: "Disconnect" })] })) : (_jsx("button", { onClick: onConnect, disabled: loading, className: "px-6 py-2 rounded-lg bg-gradient-to-r from-pink-500 to-purple-600 hover:from-pink-600 hover:to-purple-700 text-white font-medium transition-colors disabled:opacity-50", children: loading ? 'Connecting...' : 'Connect' })) })] }), _jsx("div", { className: "md:hidden flex gap-1 pb-4 overflow-x-auto", children: TABS.map(({ path, label }) => (_jsx(NavLink, { to: path, end: path === '/mining/pools', className: ({ isActive }) => `px-4 py-2 rounded-lg font-medium transition-colors whitespace-nowrap ${isActive ? 'text-white bg-slate-700' : 'text-gray-400 hover:text-white hover:bg-slate-800'}`, children: label }, path))) })] }) }));
};
